pdesire = input("enter your position desire: ")
name = input("enter your full name: ")
date = input("enter the date you filled this: ")
gender = input("tell us your gender: ")
sadd = input("your street address: ")
cadd = input("your city address: ")
padd = input("your province address: ")
tphone = input("What is your telephone number? ")
cphone = input("What is your cellphone number? ")
email = input("What is your your email address? ")
dbirth = input("When is your birth date? ")
pbirth = input("Which place were you born? ")
cstatus = input("What is your civil status? ")
ctznshp = input("What is your nationality? ")
height = input("Enter what is your height: ")
weight = input("Enter your weight: ")
religion = input("What is your religion? ")
spouse = input("What is the name of your spouse? ")
occup = input("What is your spouse occupation? ")
spobdate = input("When is your spouse born? ")
numofchil = input("How many is your children? ")
chilname = input("What is the name of your children? ")
chilbdate = input("Enter the birthdate of your children: ")
fname = input("Enter the full name of your father: ")
foccup = input("What is your father's occupation? ")
mname = input("Enter the fullname of your mother: ")
moccup = input("What is your mother's occupation? ")
gname = input("Please input the name of the person to be contacted in case of emergency: ")
rel = input("What is your relation of your guardian? ")
gadd = input("What is the address of your guardian? ")
gphone = input("Enter the phone number of your guardian: ")
elem = input("Enter the school you graduated in elementary: ")
ygradel = input("Enter the year you graduated in elementary: ")
hs = input("Enter the school you graduated in high school: ")
ygradhs = input("Enter the year you graduated in high school: ")
shs = input("Enter the school you graduated in senior high school: ")
ygradshs = input("Enter the year you graduated in senior high school: ")
tertiary = input("Enter the university or school you graduated or enter in college level: ")
ygradter = input("Enter the year you graduated in college: ")
degree = input("What is the degree that you received? ")
sskill = input("What are your special skills? ")
compname = input("What is the company name that you've worked before? ")
compos = input("What is your position at your previous work before? ")
workper = input("Enter how long you work there: ")
charrefname = input("Enter the name that knows you well to support your application job: ")
refercomp = input("Enter the name of the company of your chosen reference: ")
posrefe = input("Enter the position of your reference: ")
contactref = input("Enter the contact number of your reference: ")

print("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------")
print("|                                                                                PERSONAL INFORMATION")

print("|   POSITION DESIRE : " + pdesire +"t\DATE            : " + date)
print("|   FULL NAME       : " + name +"                                       GENDER          : " + gender)
print("|   STREET ADDRESS  : " + sadd)
print("|   CITY ADDRESS    : " + cadd)
print("|   PROVINCE ADDRESS: " + padd)
print("|   TELEPHONE NUMBER: " + tphone +"                                     CELLPHONE NUMBER: " + cphone)
print("|   EMAIL ADDRESS   : " + email)
print("|   DATE OF BIRTH   : " + dbirth +"                                     BIRTH PLACE     : " + pbirth)
print("|   STREET ADRESS   : " + sadd +"                                       CITY ADDRESS    : " + cadd)
print("|   PROVINCE ADDRESS: " + padd +"                                       ")                                        


